name: Build project

on: [push]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "build project"
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        bash -c 'cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON ..'
        make

    - name: "tests with ASAN"
      run: |
        cd build
        bash -c 'cmake  -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DASAN_BUILD=ON -DTSAN_BUILD=OFF ..'
        make
        ctest -VV

    - name: "tests with TSAN"
      run: |
        cd build
        bash -c 'cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DASAN_BUILD=OFF -DTSAN_BUILD=ON ..'
        make
        ctest -VV
