name: CI

on: [push]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: apt dependencies
      run: |
        sudo apt update
        sudo apt install -y ninja-build libeigen3-dev libspdlog-dev

    - name: catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2 && mkdir build && cd build
        cmake -Bbuild -H. -DBUILD_TESTING=OFF ..
        sudo cmake --build build/ --target install

    - name: "build project"
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        bash -c 'cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON ..'
        ninja

    - name: "tests with ASAN"
      run: |
        cd build
        bash -c 'cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DASAN_BUILD=ON -DTSAN_BUILD=OFF ..'
        ninja
        ctest -VV

    - name: "tests with TSAN"
      run: |
        cd build
        bash -c 'cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DASAN_BUILD=OFF -DTSAN_BUILD=ON ..'
        ninja
        ctest -VV
